SELECT * FROM gold.dim_customers;

SELECT * FROM gold.dim_products
LIMIT 1000;

SELECT * FROM gold.fact_sales
LIMIT 1000;

-- Find total customers by countries

SELECT customer_country country,
		COUNT(*) total_customers 
FROM gold.dim_customers
GROUP BY customer_country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT customer_gender gender,
		COUNT(*) total_customers 
FROM gold.dim_customers
GROUP BY customer_gender;

-- Find total products by category
SELECT product_category category,
		COUNT(product_id) total_categories
FROM gold.dim_products
GROUP BY product_category;

-- What is the average costs in each category?
SELECT product_category category,
		ROUND(AVG(product_cost),2) average_Cost
FROM gold.dim_products
GROUP BY product_category;

-- What is the total revenue generated for each category?
SELECT --s.*,p.*
		p.product_category,
	   SUM(p.product_cost*s.sls_quantity) tot_cost,
	   SUM(s.sls_price) tot_sales,
	   (SUM(s.sls_price)-SUM(p.product_cost*s.sls_quantity)) revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
--WHERE s.sls_quantity != 1;
GROUP BY p.product_category;

SELECT * FROM gold.dim_products WHERE product_category IS NULL;

SELECT * FROM gold.fact_sales 
where product_key IN (SELECT product_key FROM gold.dim_products WHERE product_category IS NULL);
--The products that has category as null didn't generate any revenue and it's not been sold

-- Find total revenue generated by each customer 

SELECT c.customer_firstname,
	   c.customer_lastname,
	   agg.revenue
FROM (SELECT 
			  s.customer_key,
			   SUM(p.product_cost*s.sls_quantity) tot_cost,
			   SUM(s.sls_price) tot_sales,
			   (SUM(s.sls_price)-SUM(p.product_cost*s.sls_quantity)) revenue
		FROM gold.fact_sales s
		LEFT JOIN gold.dim_products p
		ON s.product_key = p.product_key
		GROUP BY s.customer_key) agg
LEFT JOIN gold.dim_customers c
ON agg.customer_key = c.customer_key;

-- What is the distribution of sold items across countries ?